In [31]:
#---general purpose libraries--
import numpy as np
import pandas as pd
import os
#----for model bulding -----------
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
#---for model evaluation
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
#--for text processing----
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
import string
import re
#---for pipelining-----
from sklearn.pipeline import Pipeline

In [32]:
#----------FUNCTION DEFINITIONS -------------------

#--function to preprocess text
#--> Removes numbers from the text
#--> Removes punctuation marks from the text
#--> Returns array
def preprocess(text):
    return re.findall(r'(?:[a-zA-Z]+[a-zA-Z\'\-]?[a-zA-Z]|[a-zA-Z]+)',text)

#--function to print performnace report-
def performance_report(true,pred):
    print(confusion_matrix(true, pred))
    print(classification_report(true, pred))
#----------FUNCTION DEFINITIONS ENDS HERE-------------------

In [33]:
#process the file which has user query and retreived procuct to create 2 create 2 different arrays product and user_query
training = open('/content/training.txt')
product=[]
user_query=[]
first_line = 1
for line in training:
    if first_line==1:
        first_line = 0
        continue
    input_txt = line.strip().split("\t")
    processed_txt = ' '.join(txt for txt in preprocess(input_txt[0]))
    product.append(processed_txt)
    user_query.append(input_txt[1])
x_train=product
y_train=user_query

In [34]:
#create pipeline for vectorizing the text(also removes stop words) input and then creating model sequentially
x_train=product
y_train=user_query

#pred_model=Pipeline([('vectorize',TfidfVectorizer(stop_words='english')),('predictive_model', MultinomialNB())])
pred_model=Pipeline([('vectorize',TfidfVectorizer(stop_words='english')),
                   ('predictive_model', RandomForestClassifier())])
pred_model.fit(x_train,y_train)

Pipeline(steps=[('vectorize', TfidfVectorizer(stop_words='english')),
                ('predictive_model', RandomForestClassifier())])

In [35]:
#--process the sample input--
#--apply preprocessing on the text
test_prdct=[]
sample_input = open('/content/Sample_Input.txt')

first_line = 1
for line in sample_input:
    if first_line==1:
        first_line = 0
        continue
    input_txt = line.strip()
    txt = ' '.join(preprocess(input_txt))
    test_prdct.append(txt)
x_test = np.array(test_prdct)

In [36]:
#--predict the corresponding query with the model
pred_query=pred_model.predict(x_test)

In [37]:
#Lets import sample output to compare with predicted output
test_user_query = []
sample_output = open('/content/Sample_Output.txt') 
for line in sample_output:
    test_user_query.append(line.strip())

In [38]:
#--create dataframe to store the predicted Vs actual result
df_predicted_vs_actual = pd.DataFrame(
    {'Product': test_prdct,
     'Actual_User_Query': test_user_query,
     'Predicted_User_Query': pred_query
    })
#df_predicted_vs_actual

In [39]:
#--print the performance report
performance_report(df_predicted_vs_actual['Actual_User_Query'],df_predicted_vs_actual['Predicted_User_Query'])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
                            precision    recall  f1-score   support

          athleisure women       0.00      0.00      0.00         1
                   axe deo       0.00      0.00      0.00         1
                   bandana       1.00      1.00      1.00         1
               beach dress       0.00      0.00      0.00         1
                   beanies       1.00      1.00      1.00         1
              biker gloves       1.00      1.00      1.00         1
              biker jacket       1.00      1.00      1.00         1
              biker shorts       0.50      1.00      0.67         1
                 bodysuits       1.00      1.00      1.00         1
           boyfriend jeans       0.50      1.00      0.67         1
                  bralette       1.00      1.00      1.00         1
          buttondown skirt       0.33      1.00      0.50      

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [40]:
#-----------------------------------------------------------------------------------------------